<?php
declare(strict_types=1);

const ROOT = __DIR__;

function env(): array {
    static $env;
    if ($env !== null) return $env;
    $file = ROOT . '/.env';
    $env = is_file($file) ? parse_ini_file($file, false, INI_SCANNER_RAW) : [];
    return $env ?: [];
}
function installed(): bool { return is_file(ROOT . '/storage/installed.lock') && env() !== []; }
function db(): PDO {
    static $pdo;
    if ($pdo) return $pdo;
    $e = env();
    $pdo = new PDO("mysql:host={$e['DB_HOST']};port={$e['DB_PORT']};dbname={$e['DB_NAME']};charset=utf8mb4", $e['DB_USER'], $e['DB_PASS'], [PDO::ATTR_ERRMODE => PDO::ERRMODE_EXCEPTION, PDO::ATTR_DEFAULT_FETCH_MODE => PDO::FETCH_ASSOC]);
    return $pdo;
}
function q(string $sql, array $values = []): PDOStatement { $s = db()->prepare($sql); $s->execute($values); return $s; }
function e(?string $value): string { return htmlspecialchars((string) $value, ENT_QUOTES, 'UTF-8'); }
function base(string $path = ''): string { $prefix = rtrim(dirname($_SERVER['SCRIPT_NAME']), '/\\'); return ($prefix === '/' ? '' : $prefix) . $path; }
function absolute_url(string $path = ''): string { $https = !empty($_SERVER['HTTPS']) && $_SERVER['HTTPS'] !== 'off'; $host = preg_replace('/[^A-Za-z0-9.:-]/', '', $_SERVER['HTTP_HOST'] ?? 'localhost'); return ($https ? 'https://' : 'http://') . $host . base($path); }
function redirect(string $path): never { header('Location: ' . base($path), true, 303); exit; }
function flash(string $key, ?string $message = null): ?string { if ($message !== null) { $_SESSION['flash'][$key] = $message; return null; } $m = $_SESSION['flash'][$key] ?? null; unset($_SESSION['flash'][$key]); return $m; }
function csrf(): string { return $_SESSION['csrf'] ??= bin2hex(random_bytes(32)); }
function check_csrf(): void { if (!hash_equals($_SESSION['csrf'] ?? '', $_POST['_csrf'] ?? '')) { http_response_code(419); exit('CSRF tidak valid.'); } }
function admin(): ?array { return $_SESSION['admin'] ?? null; }
function auth(): void { if (!admin()) redirect('/admin/login'); }
function post_only(): void { if (($_SERVER['REQUEST_METHOD'] ?? '') !== 'POST') { http_response_code(405); exit('Method tidak diizinkan.'); } }
function valid_product_type(string $type): bool { return in_array($type, ['file_link', 'account_stock', 'manual'], true); }
function valid_delivery_url(string $url): bool { return $url === '' || (filter_var($url, FILTER_VALIDATE_URL) && in_array(strtolower((string) parse_url($url, PHP_URL_SCHEME)), ['https'], true)); }
function appearance(): array { return installed() ? q('SELECT `key`,value FROM settings WHERE `key` LIKE "theme_%" OR `key` LIKE "hero_%" OR `key` LIKE "store_%" OR `key` LIKE "catalog_%" OR `key` LIKE "footer_%"')->fetchAll(PDO::FETCH_KEY_PAIR) : []; }
function hex_color(string $value, string $fallback): string { return preg_match('/^#[0-9a-fA-F]{6}$/',$value) ? $value : $fallback; }
function token(int $bytes = 24): string { return rtrim(strtr(base64_encode(random_bytes($bytes)), '+/', '-_'), '='); }
function encrypt_stock(string $value): string { $key = hash('sha256', env()['APP_KEY'], true); $iv = random_bytes(12); $tag = ''; $cipher = openssl_encrypt($value, 'aes-256-gcm', $key, OPENSSL_RAW_DATA, $iv, $tag); return base64_encode($iv . $tag . $cipher); }
function decrypt_stock(string $value): string { $raw = base64_decode($value, true); $key = hash('sha256', env()['APP_KEY'], true); return openssl_decrypt(substr($raw, 28), 'aes-256-gcm', $key, OPENSSL_RAW_DATA, substr($raw, 0, 12), substr($raw, 12, 16)) ?: ''; }
function view(string $title, string $content, bool $adminArea = false): never {
    $notice = flash('success'); $error = flash('error'); $look=$adminArea?[]:appearance(); $brand = $look['store_name'] ?? (installed() ? (q('SELECT value FROM settings WHERE `key` = "store_name"')->fetchColumn() ?: 'Toko Digital') : 'Toko Digital');
    ?><!doctype html><html lang="id"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title><?=e($title)?> | <?=e($brand)?></title><style>
    @import url('https://fonts.googleapis.com/css2?family=DM+Mono:wght@400;500&family=Fraunces:opsz,wght@9..144,600;9..144,700&display=swap');
    <?php if (!$adminArea): ?>:root{--ink:<?=hex_color($look['theme_primary']??'', '#17231e')?>;--paper:<?=hex_color($look['theme_background']??'', '#f3f0e8')?>;--lime:<?=hex_color($look['theme_accent']??'', '#c8f45c')?>}<?php endif ?>
    .nav{position:sticky;top:0;z-index:10;background:var(--paper)}
    <?php if ($adminArea): ?>
    :root{--admin:#101a17;--admin-soft:#e8efe8;--blue:#2563eb;--white:#fff}.admin-shell{min-height:calc(100vh - 74px);padding-left:245px}.admin-aside{background:var(--admin);color:#dce7df;padding:28px 18px;position:fixed;z-index:2;left:0;top:74px;bottom:0;width:245px;overflow-y:auto}.admin-aside__label{font-size:10px;color:#92a49a;text-transform:uppercase;letter-spacing:.12em;margin:0 10px 13px}.admin-nav{display:grid;gap:4px;margin:0;padding:0;border:0}.admin-nav a{padding:11px 12px;border-radius:7px;text-decoration:none;color:#dce7df}.admin-nav a:hover,.admin-nav a.current{background:#2a3a34;color:#fff}.admin-main{min-width:0;max-width:1280px;padding:42px 5vw 64px}.admin-main .hero{padding:0 0 25px;margin-bottom:26px}.admin-main h1{font-size:clamp(35px,4vw,58px)}.admin-main .grid{grid-template-columns:repeat(3,minmax(0,1fr));margin-top:0}.metric{border:1px solid #c8d4cb;border-radius:10px;padding:20px;background:#fff;display:grid;gap:8px}.metric strong{font:700 34px Fraunces,serif}.metric span{font-size:12px;color:#5c6d63}.panel{border-color:#c8d4cb;border-radius:10px;box-shadow:0 2px 0 rgba(23,35,30,.04)}.table-wrap{border:1px solid #c8d4cb;border-radius:10px;overflow:auto;background:#fff}.table{border:0;min-width:640px}.table th{background:#e8efe8;font-size:11px;text-transform:uppercase;letter-spacing:.06em}.table th,.table td{border-color:#dce5df}.status{display:inline-flex;padding:4px 8px;border-radius:999px;font-size:11px;background:#e8efe8;color:#31503d}.status.pending{background:#fff1c7;color:#805b00}.status.fulfilled,.status.paid{background:#d8f5dc;color:#17612b}.status.cancelled,.status.expired{background:#fde0d9;color:#9b2c1b}.page-actions{display:flex;gap:10px;align-items:center;justify-content:space-between;margin-bottom:22px}.page-actions .btn{white-space:nowrap}.admin-main form{max-width:none}.admin-main input,.admin-main select,.admin-main textarea{border-color:#aebcb3;border-radius:6px}.admin-main button,.admin-main .btn{border-radius:6px}.form-section{padding:20px;border:1px solid #c8d4cb;border-radius:10px;background:#fff;margin-bottom:18px}.form-section h2{font-size:25px}.form-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:14px}.form-grid .full{grid-column:1/-1}.empty{padding:32px;border:1px dashed #aebcb3;border-radius:10px;color:#5c6d63;text-align:center}.modal{border:0;border-radius:12px;padding:0;width:min(460px,calc(100% - 32px));background:#fff}.modal::backdrop{background:rgba(16,26,23,.65)}.modal-card{padding:26px}.modal-card form{max-width:none}@media(max-width:800px){.admin-shell{display:block;padding-left:0}.admin-aside{position:static;width:auto;height:auto;padding:14px 5vw}.admin-aside__label{display:none}.admin-nav{display:flex;overflow-x:auto;gap:6px}.admin-nav a{white-space:nowrap}.admin-main{padding:28px 5vw}.admin-main .grid{grid-template-columns:1fr}.form-grid{grid-template-columns:1fr}.page-actions{align-items:flex-start;flex-direction:column}.admin-main .hero{margin-bottom:18px}}
    <?php endif ?>
    :root{--ink:#17231e;--paper:#f3f0e8;--lime:#c8f45c;--rust:#d65331;--line:#c8c4b8}*{box-sizing:border-box}body{margin:0;background:var(--paper);color:var(--ink);font:15px 'DM Mono',monospace}a{color:inherit}.nav{display:flex;justify-content:space-between;gap:20px;padding:22px 6vw;border-bottom:1px solid var(--line);align-items:center}.brand{font:700 24px Fraunces,serif;text-decoration:none}.nav a{text-decoration:none}.wrap{max-width:1100px;margin:auto;padding:46px 6vw}.hero{padding:44px 0 32px;border-bottom:1px solid var(--line)}h1,h2{font-family:Fraunces,serif;line-height:1;margin:0 0 18px}h1{font-size:clamp(40px,7vw,78px);max-width:820px}h2{font-size:30px}.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(230px,1fr));gap:18px;margin-top:30px}.card,.panel{border:1px solid var(--ink);padding:22px;background:#fffdf8}.card{min-height:200px;display:flex;flex-direction:column;justify-content:space-between;text-decoration:none}.type{font-size:11px;text-transform:uppercase;color:#617069}.price{font:700 25px Fraunces,serif}.btn,button{background:var(--ink);color:white;border:1px solid var(--ink);padding:12px 16px;font:inherit;cursor:pointer;text-decoration:none;display:inline-block}.btn.lime{background:var(--lime);color:var(--ink)}form{display:grid;gap:13px;max-width:640px}label{display:grid;gap:7px}input,select,textarea{width:100%;padding:12px;border:1px solid var(--ink);background:#fffdf8;font:inherit}textarea{min-height:115px}.notice{padding:14px;margin-bottom:18px;background:var(--lime);border:1px solid var(--ink)}.error{background:#ffd1c7}.admin-nav{display:flex;flex-wrap:wrap;gap:12px;margin-bottom:32px;border-bottom:1px solid var(--line);padding-bottom:16px}.table{width:100%;border-collapse:collapse;background:#fffdf8}.table th,.table td{text-align:left;padding:12px;border:1px solid var(--line);vertical-align:top}.muted{color:#617069;font-size:13px}.split{display:grid;grid-template-columns:1fr 1fr;gap:35px}.code{overflow-wrap:anywhere;background:#ece8de;padding:12px}@media(max-width:650px){.split{grid-template-columns:1fr}.wrap{padding-top:28px}.table{font-size:12px}}
    </style></head><body><nav class="nav"><a class="brand" href="<?=base('/')?>"><?php if(!$adminArea&&!empty($look['store_logo'])):?><img src="<?=base($look['store_logo'])?>" alt="<?=e($brand)?>" style="height:32px;max-width:160px;object-fit:contain;vertical-align:middle"><?php else: ?><?=e($brand)?><?php endif ?></a><?php if($adminArea): ?><span><form method="post" action="<?=base('/admin/logout')?>" style="display:inline"><input type="hidden" name="_csrf" value="<?=csrf()?>"><button type="submit" style="padding:0;border:0;background:none;color:inherit">Keluar</button></form></span><?php endif ?></nav><?php if($adminArea): ?><div class="admin-shell"><aside class="admin-aside"><p class="admin-aside__label">Operasional toko</p><nav class="admin-nav" style="display:grid;grid-template-columns:1fr;flex-wrap:nowrap"><a class="<?=($_SERVER['REQUEST_URI']===base('/admin')?'current':'')?>" href="<?=base('/admin')?>">Ringkasan</a><a class="<?=str_contains($_SERVER['REQUEST_URI'],'/admin/products')?'current':''?>" href="<?=base('/admin/products')?>">Produk</a><a class="<?=str_contains($_SERVER['REQUEST_URI'],'/admin/stocks')?'current':''?>" href="<?=base('/admin/stocks')?>">Stok</a><a class="<?=str_contains($_SERVER['REQUEST_URI'],'/admin/orders')?'current':''?>" href="<?=base('/admin/orders')?>">Pesanan</a><a class="<?=str_contains($_SERVER['REQUEST_URI'],'/admin/appearance')?'current':''?>" href="<?=base('/admin/appearance')?>">Tampilan</a><a class="<?=str_contains($_SERVER['REQUEST_URI'],'/admin/settings')?'current':''?>" href="<?=base('/admin/settings')?>">Pengaturan</a></nav></aside><main class="admin-main"><?php else: ?><main class="wrap"><?php endif ?><?php if($notice): ?><div class="notice"><?=e($notice)?></div><?php endif ?><?php if($error): ?><div class="notice error"><?=e($error)?></div><?php endif ?><?=$content?></main><?php if($adminArea): ?></div><?php endif ?></body></html><?php exit;
}
