<?php
declare(strict_types=1);
session_name('zenhosta_session'); session_start(['cookie_httponly' => true, 'cookie_samesite' => 'Lax', 'cookie_secure' => (!empty($_SERVER['HTTPS']) && $_SERVER['HTTPS'] !== 'off')]);
require __DIR__ . '/app.php';
ini_set('display_errors', '0');
header('X-Content-Type-Options: nosniff');
header('X-Frame-Options: DENY');
header('Referrer-Policy: strict-origin-when-cross-origin');
header('Permissions-Policy: camera=(), microphone=(), geolocation=()');
$method = $_SERVER['REQUEST_METHOD'];
$path = '/' . trim(parse_url($_SERVER['REQUEST_URI'], PHP_URL_PATH) ?? '/', '/');
$scriptDir = rtrim(str_replace('\\', '/', dirname($_SERVER['SCRIPT_NAME'])), '/');
if ($scriptDir && str_starts_with($path, $scriptDir)) $path = substr($path, strlen($scriptDir)) ?: '/';

if (!installed() && !str_starts_with($path, '/install')) redirect('/install');
if (installed() && str_starts_with($path, '/install')) redirect('/');

if ($path === '/install' && $method === 'GET') {
    $checks=installer_checks(); $rows=''; $ready=true; foreach($checks as $check){$ready=$ready && $check['ok'];$rows.='<tr><td>'.e($check['name']).'</td><td>'.e($check['value']).'</td><td>'.($check['ok']?'Siap':'Gagal').'</td></tr>';}
    $button=$ready?'<a class="btn lime" href="'.base('/install/database').'">Lanjut konfigurasi database</a>':'<p class="muted">Perbaiki semua pemeriksaan gagal sebelum lanjut.</p>';
    installer_view('1. Pemeriksaan server','<h1>Server siap?</h1><p>PHP, extension, dan izin folder diperiksa sebelum database diatur.</p>','<section class="panel"><table class="table"><tr><th>Pemeriksaan</th><th>Nilai</th><th>Status</th></tr>'.$rows.'</table><p>'.$button.'</p></section>');
}
if ($path === '/install/database' && $method === 'GET') {
    if (!installer_ready()) redirect('/install'); $v=$_SESSION['install']['db']??[];
    installer_view('2. Database','<h1>Hubungkan MySQL.</h1><p>Koneksi diuji sekarang. Tabel dibuat setelah lisensi valid.</p>','<section class="panel"><form method="post"><input type="hidden" name="_csrf" value="'.csrf().'"><label>Host MySQL<input name="db_host" value="'.e($v['host']??'localhost').'" required></label><label>Port<input name="db_port" type="number" value="'.e($v['port']??'3306').'" required></label><label>Nama database<input name="db_name" value="'.e($v['name']??'').'" required></label><label>User database<input name="db_user" value="'.e($v['user']??'').'" required></label><label>Password database<input name="db_pass" type="password" required></label><label>Nama toko<input name="store_name" value="'.e($v['store_name']??'').'" required></label><button>Uji koneksi dan lanjut</button></form></section>');
}
if ($path === '/install/database' && $method === 'POST') {
    check_csrf(); if (!installer_ready()) redirect('/install'); $data=['host'=>trim($_POST['db_host']),'port'=>(int)$_POST['db_port'],'name'=>trim($_POST['db_name']),'user'=>trim($_POST['db_user']),'pass'=>$_POST['db_pass']??'','store_name'=>trim($_POST['store_name'])];
    try { if(!preg_match('/^[A-Za-z0-9_]+$/',$data['name']))throw new RuntimeException('Nama database hanya boleh huruf, angka, dan underscore.'); $pdo=new PDO("mysql:host={$data['host']};port={$data['port']};charset=utf8mb4",$data['user'],$data['pass'],[PDO::ATTR_ERRMODE=>PDO::ERRMODE_EXCEPTION]); $pdo->exec('CREATE DATABASE IF NOT EXISTS `'.str_replace('`','``',$data['name']).'` CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci'); $_SESSION['install']['db']=$data; redirect('/install/admin'); } catch(Throwable $e){flash('error','Koneksi MySQL atau pembuatan database gagal: '.$e->getMessage());redirect('/install/database');}
}
if ($path === '/install/admin' && $method === 'GET') {
    if (empty($_SESSION['install']['db'])) redirect('/install/database'); $v=$_SESSION['install']['admin']??[];
    installer_view('3. Admin','<h1>Buat admin awal.</h1><p>Akun ini mendapat akses penuh ke panel toko.</p>','<section class="panel"><form method="post"><input type="hidden" name="_csrf" value="'.csrf().'"><label>Email admin<input name="admin_email" type="email" value="'.e($v['email']??'').'" required></label><label>Password admin<input name="admin_password" type="password" minlength="10" required></label><label>Ulangi password<input name="admin_password_confirm" type="password" minlength="10" required></label><button>Lanjut lisensi</button></form></section>');
}
if ($path === '/install/admin' && $method === 'POST') {
    check_csrf(); if(empty($_SESSION['install']['db']))redirect('/install/database'); $pass=$_POST['admin_password']??''; if(!filter_var($_POST['admin_email']??'',FILTER_VALIDATE_EMAIL)||strlen($pass)<10||$pass!==($_POST['admin_password_confirm']??'')){flash('error','Email tidak valid atau password minimal 10 karakter dan harus sama.');redirect('/install/admin');} $_SESSION['install']['admin']=['email'=>trim($_POST['admin_email']),'password'=>$pass];redirect('/install/license');
}
if ($path === '/install/license' && $method === 'GET') {
    if(empty($_SESSION['install']['db'])||empty($_SESSION['install']['admin']))redirect('/install'); installer_view('4. Lisensi','<h1>Aktifkan lisensi.</h1><p>Setelah valid, schema database dibuat dan instalasi dikunci.</p>','<section class="panel"><form method="post"><input type="hidden" name="_csrf" value="'.csrf().'"><label>Kode lisensi<input name="license" required autofocus></label><button>Install toko</button></form></section>');
}
if ($path === '/install/license' && $method === 'POST') {
    check_csrf(); $setup=$_SESSION['install']??[]; if(empty($setup['db'])||empty($setup['admin']))redirect('/install'); if(!hash_equals('zenhosta',trim($_POST['license']??''))){flash('error','Kode lisensi tidak valid.');redirect('/install/license');} $d=$setup['db'];
    try{$pdo=new PDO("mysql:host={$d['host']};port={$d['port']};charset=utf8mb4",$d['user'],$d['pass'],[PDO::ATTR_ERRMODE=>PDO::ERRMODE_EXCEPTION]);$pdo->exec('CREATE DATABASE IF NOT EXISTS `'.str_replace('`','``',$d['name']).'` CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci');$pdo->exec('USE `'.str_replace('`','``',$d['name']).'`');$pdo->exec((string)file_get_contents(ROOT.'/database/schema.sql'));$key=bin2hex(random_bytes(32));$env="DB_HOST=\"{$d['host']}\"\nDB_PORT=\"{$d['port']}\"\nDB_NAME=\"{$d['name']}\"\nDB_USER=\"{$d['user']}\"\nDB_PASS=\"".addcslashes($d['pass'],'"\\')."\"\nAPP_KEY=\"$key\"\n";if(file_put_contents(ROOT.'/.env',$env,LOCK_EX)===false)throw new RuntimeException('Gagal menulis .env.');@chmod(ROOT.'/.env',0600);$pdo->prepare('INSERT INTO admins (email,password) VALUES (?,?)')->execute([$setup['admin']['email'],password_hash($setup['admin']['password'],PASSWORD_DEFAULT)]);$pdo->prepare('INSERT INTO settings (`key`,value) VALUES (?,?),(?,?),(?,?)')->execute(['store_name',$d['store_name'],'license_hash',password_hash('zenhosta',PASSWORD_DEFAULT),'currency','IDR']);if(file_put_contents(ROOT.'/storage/installed.lock',date(DATE_ATOM))===false)throw new RuntimeException('Gagal mengunci installer.');unset($_SESSION['install']);redirect('/admin/login');}catch(Throwable $e){flash('error','Instalasi gagal: '.$e->getMessage());redirect('/install/license');}
}

if ($path === '/admin/login' && $method === 'GET') view('Login admin','<section class="hero"><p class="type">Admin access</p><h1>Masuk panel.</h1></section><section class="panel" style="margin-top:30px"><form method="post"><input type="hidden" name="_csrf" value="'.csrf().'"><label>Email<input name="email" type="email" required></label><label>Password<input name="password" type="password" required></label><button>Masuk</button></form></section>');
if ($path === '/admin/login' && $method === 'POST') { check_csrf(); $a=q('SELECT id,email,password FROM admins WHERE email=? AND active=1',[trim($_POST['email'])])->fetch(); if (!$a || !password_verify($_POST['password'],$a['password'])) { flash('error','Email atau password salah.'); redirect('/admin/login'); } session_regenerate_id(true); $_SESSION['admin']=['id'=>$a['id'],'email'=>$a['email']]; redirect('/admin'); }
if ($path === '/admin/logout' && $method === 'POST') { auth(); check_csrf(); $_SESSION=[]; session_destroy(); redirect('/'); }

if ($path === '/' && $method === 'GET') { $cards=''; foreach(q('SELECT * FROM products WHERE active=1 ORDER BY id DESC')->fetchAll() as $p) $cards.='<a class="card" href="'.base('/produk/'.rawurlencode($p['slug'])).'"><div><p class="type">'.e($p['type']).'</p><h2>'.e($p['name']).'</h2><p>'.e(mb_strimwidth($p['description'],0,110,'...')).'</p></div><span class="price">Rp '.number_format((int)$p['price'],0,',','.').'</span></a>'; view('Katalog','<section class="hero"><p class="type">Produk digital siap kirim</p><h1>Beli sekali. Terima langsung.</h1><p>Ebook, video, link digital, dan stok akun.</p></section><section class="grid">'.($cards ?: '<p>Belum ada produk aktif.</p>').'</section>'); }
if (preg_match('#^/produk/([^/]+)$#',$path,$m) && $method==='GET') { $p=q('SELECT * FROM products WHERE slug=? AND active=1',[urldecode($m[1])])->fetch(); if(!$p){http_response_code(404);view('Tidak ditemukan','<h1>Produk tidak ditemukan.</h1>');} $fields=q('SELECT * FROM product_fields WHERE product_id=? ORDER BY sort_order,id',[$p['id']])->fetchAll(); $form='<label>Nama<input name="buyer_name" required></label><label>Email untuk menerima produk<input name="buyer_email" type="email" required></label>'; foreach($fields as $f){$req=$f['required']?'required':''; $form.='<label>'.e($f['label']).($f['type']==='textarea'?'<textarea name="field['.$f['id'].']" '.$req.'></textarea>':'<input name="field['.$f['id'].']" type="'.e($f['type']).'" '.$req.'>'); $form.='</label>'; } view($p['name'],'<div class="split"><section class="hero"><p class="type">'.e($p['type']).'</p><h1>'.e($p['name']).'</h1><p>'.nl2br(e($p['description'])).'</p><p class="price">Rp '.number_format((int)$p['price'],0,',','.').'</p></section><section class="panel"><h2>Checkout tanpa akun</h2><form method="post" action="'.base('/checkout/'.$p['id']).'"><input type="hidden" name="_csrf" value="'.csrf().'">'.$form.'<button>Buat pembayaran</button></form></section></div>'); }
if (preg_match('#^/checkout/(\d+)$#',$path,$m) && $method==='POST') { check_csrf(); $p=q('SELECT * FROM products WHERE id=? AND active=1',[(int)$m[1]])->fetch(); if(!$p){flash('error','Produk tidak tersedia.');redirect('/');} $name=trim($_POST['buyer_name']??'');$email=trim($_POST['buyer_email']??'');if($name===''||!filter_var($email,FILTER_VALIDATE_EMAIL)){flash('error','Nama dan email valid wajib diisi.');redirect('/produk/'.$p['slug']);} $fields=q('SELECT id,required FROM product_fields WHERE product_id=?',[$p['id']])->fetchAll();foreach($fields as $field)if($field['required']&&trim($_POST['field'][$field['id']]??'')===''){flash('error','Field wajib belum diisi.');redirect('/produk/'.$p['slug']);} if($p['type']==='account_stock' && !q("SELECT id FROM stock_items WHERE product_id=? AND status='available' LIMIT 1",[$p['id']])->fetch()){flash('error','Stok sedang habis.');redirect('/produk/'.$p['slug']);} $invoice='ZTH-'.date('Ymd').'-'.strtoupper(substr(token(6),0,8)); $orderToken=token(); db()->beginTransaction(); try{ q('INSERT INTO orders (invoice,access_token,buyer_name,buyer_email,total,status) VALUES (?,?,?,?,?,"pending")',[$invoice,$orderToken,$name,$email,$p['price']]); $oid=(int)db()->lastInsertId(); q('INSERT INTO order_items (order_id,product_id,product_name,product_type,price,delivery_url) VALUES (?,?,?,?,?,?)',[$oid,$p['id'],$p['name'],$p['type'],$p['price'],$p['delivery_url']]); foreach(($_POST['field']??[]) as $fid=>$value) q('INSERT INTO order_field_values (order_id,field_id,value) VALUES (?,?,?)',[$oid,(int)$fid,trim($value)]); db()->commit(); redirect('/invoice/'.$orderToken); }catch(Throwable $ex){db()->rollBack();throw $ex;} }
if (preg_match('#^/invoice/([A-Za-z0-9_-]+)$#',$path,$m) && $method==='GET') { $o=q('SELECT * FROM orders WHERE access_token=?',[$m[1]])->fetch(); if(!$o){http_response_code(404);view('Tidak ditemukan','<h1>Invoice tidak ditemukan.</h1>');} $settings=q('SELECT `key`,value FROM settings WHERE `key` IN ("pakasir_slug","pakasir_qris_only")')->fetchAll(PDO::FETCH_KEY_PAIR); $pay=''; if($o['status']==='pending' && !empty($settings['pakasir_slug'])){$url='https://app.pakasir.com/pay/'.rawurlencode($settings['pakasir_slug']).'/'.$o['total'].'?order_id='.rawurlencode($o['invoice']).'&redirect='.rawurlencode(absolute_url('/invoice/'.$o['access_token'])); if(($settings['pakasir_qris_only']??'')==='1')$url.='&qris_only=1'; $pay='<a class="btn lime" href="'.e($url).'">Bayar dengan Pakasir</a>';} $item=q('SELECT * FROM order_items WHERE order_id=?',[$o['id']])->fetch(); view('Invoice '.$o['invoice'],'<section class="hero"><p class="type">Invoice '.e($o['invoice']).'</p><h1>'.e(ucfirst($o['status'])).'</h1><p>'.e($item['product_name']).' · Rp '.number_format((int)$o['total'],0,',','.').'</p>'.$pay.'</section><section class="panel" style="margin-top:30px"><p>Produk dikirim ke <strong>'.e($o['buyer_email']).'</strong> setelah pembayaran terverifikasi.</p></section>'); }

if ($path === '/admin' && $method === 'GET') { auth(); $counts=q("SELECT status,COUNT(*) total FROM orders GROUP BY status")->fetchAll(); $text='';foreach($counts as $c)$text.='<p><strong>'.e($c['status']).'</strong>: '.e($c['total']).'</p>'; view('Dashboard','<section class="hero"><p class="type">Panel toko</p><h1>Operasional ringkas.</h1></section><section class="grid"><div class="panel"><h2>Pesanan</h2>'.$text.'</div><div class="panel"><h2>Stok tersedia</h2><p class="price">'.q("SELECT COUNT(*) FROM stock_items WHERE status='available'")->fetchColumn().'</p></div></section>',true); }
if ($path === '/admin/products' && $method === 'GET') { auth(); $rows='';foreach(q('SELECT * FROM products ORDER BY id DESC')->fetchAll() as $p)$rows.='<tr><td>'.e($p['name']).'<br><span class="muted">'.e($p['type']).'</span></td><td>Rp '.number_format((int)$p['price'],0,',','.').'</td><td><a href="'.base('/admin/products/'.$p['id']).'">Edit</a></td></tr>'; view('Produk','<section class="hero"><p class="type">Katalog</p><h1>Produk.</h1><p><a class="btn lime" href="'.base('/admin/products/new').'">Tambah produk</a></p></section><table class="table"><tr><th>Produk</th><th>Harga</th><th></th></tr>'.$rows.'</table>',true); }
if ($path === '/admin/products/new' && $method === 'GET') { auth(); view('Tambah produk',product_form(),true); }
if ($path === '/admin/products/new' && $method === 'POST') { auth();check_csrf(); $type=$_POST['type']??'';$url=trim($_POST['delivery_url']??'');if(trim($_POST['name']??'')===''||!valid_product_type($type)||!valid_delivery_url($url)){flash('error','Data produk tidak valid. Link pengiriman wajib HTTPS.');redirect('/admin/products/new');}$slug=slug($_POST['name']); q('INSERT INTO products (slug,name,type,description,price,delivery_url,active) VALUES (?,?,?,?,?,?,?)',[$slug,trim($_POST['name']),$type,trim($_POST['description']),max(0,(int)$_POST['price']),$url,isset($_POST['active'])]); flash('success','Produk dibuat. Tambah field checkout atau stok bila perlu.');redirect('/admin/products/'.db()->lastInsertId()); }
if (preg_match('#^/admin/products/(\d+)$#',$path,$m) && $method==='GET') { auth();$p=q('SELECT * FROM products WHERE id=?',[(int)$m[1]])->fetch();if(!$p){http_response_code(404);exit('Tidak ditemukan');}$fields='';foreach(q('SELECT * FROM product_fields WHERE product_id=? ORDER BY sort_order,id',[$p['id']])->fetchAll() as $f)$fields.='<li>'.e($f['label']).' ('.e($f['type']).') <a href="'.base('/admin/fields/'.$f['id'].'/delete').'">hapus</a></li>'; $stocks=$p['type']==='account_stock'?'<section class="panel"><h2>Stok akun</h2><p>Tulis satu akun per baris. Data terenkripsi saat disimpan.</p><form method="post" action="'.base('/admin/products/'.$p['id'].'/stocks').'" ><input type="hidden" name="_csrf" value="'.csrf().'"><textarea name="stock" placeholder="email:password atau format bebas" required></textarea><button>Tambah stok</button></form><p>Tersedia: '.q("SELECT COUNT(*) FROM stock_items WHERE product_id=? AND status='available'",[$p['id']])->fetchColumn().'</p></section>':''; view('Edit produk','<section class="hero"><p class="type">'.e($p['type']).'</p><h1>'.e($p['name']).'</h1></section><div class="split"><section class="panel">'.product_form($p,'/admin/products/'.$p['id']).'</section><section><section class="panel"><h2>Field checkout tambahan</h2><ul>'.$fields.'</ul><form method="post" action="'.base('/admin/products/'.$p['id'].'/fields').'" ><input type="hidden" name="_csrf" value="'.csrf().'"><label>Label<input name="label" required></label><label>Tipe<select name="type"><option>text</option><option>email</option><option>tel</option><option>textarea</option></select></label><label><input type="checkbox" name="required" value="1"> Wajib diisi</label><button>Tambah field</button></form></section>'.$stocks.'</section></div>',true); }
if (preg_match('#^/admin/products/(\d+)$#',$path,$m) && $method==='POST') {auth();check_csrf();$type=$_POST['type']??'';$url=trim($_POST['delivery_url']??'');if(trim($_POST['name']??'')===''||!valid_product_type($type)||!valid_delivery_url($url)){flash('error','Data produk tidak valid. Link pengiriman wajib HTTPS.');redirect('/admin/products/'.$m[1]);}q('UPDATE products SET name=?,type=?,description=?,price=?,delivery_url=?,active=? WHERE id=?',[trim($_POST['name']),$type,trim($_POST['description']),max(0,(int)$_POST['price']),$url,isset($_POST['active']),(int)$m[1]]);flash('success','Produk diperbarui.');redirect('/admin/products/'.$m[1]);}
if (preg_match('#^/admin/products/(\d+)/fields$#',$path,$m) && $method==='POST'){auth();check_csrf();q('INSERT INTO product_fields(product_id,label,type,required) VALUES(?,?,?,?)',[(int)$m[1],trim($_POST['label']),$_POST['type'],isset($_POST['required'])]);redirect('/admin/products/'.$m[1]);}
if (preg_match('#^/admin/fields/(\d+)/delete$#',$path,$m) && $method==='POST'){auth();check_csrf();$pid=q('SELECT product_id FROM product_fields WHERE id=?',[(int)$m[1]])->fetchColumn();q('DELETE FROM product_fields WHERE id=?',[(int)$m[1]]);redirect('/admin/products/'.$pid);}
if (preg_match('#^/admin/products/(\d+)/stocks$#',$path,$m) && $method==='POST'){auth();check_csrf();$lines=preg_split('/\R/',trim($_POST['stock']));foreach($lines as $line)if(trim($line)!=='')q('INSERT INTO stock_items(product_id,payload) VALUES(?,?)',[(int)$m[1],encrypt_stock(trim($line))]);flash('success',count($lines).' stok ditambahkan.');redirect('/admin/products/'.$m[1]);}
if ($path==='/admin/orders' && $method==='GET'){auth();$rows='';foreach(q('SELECT * FROM orders ORDER BY id DESC LIMIT 100')->fetchAll() as $o)$rows.='<tr><td>'.e($o['invoice']).'<br><span class="muted">'.e($o['buyer_email']).'</span></td><td>'.e($o['status']).'</td><td>Rp '.number_format((int)$o['total'],0,',','.').'</td><td>'.e($o['created_at']).'</td></tr>';view('Pesanan','<section class="hero"><p class="type">Order terakhir</p><h1>Pesanan.</h1></section><table class="table"><tr><th>Invoice</th><th>Status</th><th>Total</th><th>Waktu</th></tr>'.$rows.'</table>',true);}
if ($path==='/admin/settings' && $method==='GET'){auth();$s=q('SELECT `key`,value FROM settings')->fetchAll(PDO::FETCH_KEY_PAIR);view('Pengaturan','<section class="hero"><p class="type">Gateway dan email</p><h1>Pengaturan.</h1></section><section class="panel"><form method="post"><input type="hidden" name="_csrf" value="'.csrf().'"><h2>Pakasir</h2><label>Project slug Pakasir<input name="pakasir_slug" value="'.e($s['pakasir_slug']??'').'"></label><label>API key Pakasir<input name="pakasir_api_key" type="password" value="'.e($s['pakasir_api_key']??'').'"></label><label><input type="checkbox" name="qris_only" value="1" '.(($s['pakasir_qris_only']??'')==='1'?'checked':'').'> Hanya QRIS</label><h2>SMTP</h2><label>SMTP host<input name="smtp_host" value="'.e($s['smtp_host']??'').'"></label><label>SMTP port<input name="smtp_port" type="number" value="'.e($s['smtp_port']??'587').'"></label><label>SMTP username<input name="smtp_user" value="'.e($s['smtp_user']??'').'"></label><label>SMTP password<input name="smtp_pass" type="password" value="'.e($s['smtp_pass']??'').'"></label><label>Email pengirim<input name="smtp_from" type="email" value="'.e($s['smtp_from']??'').'"></label><label>Nama pengirim<input name="smtp_name" value="'.e($s['smtp_name']??'').'"></label><p class="muted">Set webhook Pakasir ke '.e(base('/webhooks/pakasir')).'. Install dependency: composer install.</p><button>Simpan</button></form></section>',true);}
if ($path==='/admin/settings' && $method==='POST'){auth();check_csrf();$values=['pakasir_slug'=>trim($_POST['pakasir_slug']),'pakasir_api_key'=>trim($_POST['pakasir_api_key']),'pakasir_qris_only'=>isset($_POST['qris_only'])?'1':'0','smtp_host'=>trim($_POST['smtp_host']),'smtp_port'=>(string)(int)$_POST['smtp_port'],'smtp_user'=>trim($_POST['smtp_user']),'smtp_pass'=>trim($_POST['smtp_pass']),'smtp_from'=>trim($_POST['smtp_from']),'smtp_name'=>trim($_POST['smtp_name'])];foreach($values as $k=>$v)q('INSERT INTO settings (`key`,value) VALUES (?,?) ON DUPLICATE KEY UPDATE value=VALUES(value)',[$k,$v]);flash('success','Pengaturan disimpan.');redirect('/admin/settings');}
if ($path==='/webhooks/pakasir' && $method==='POST'){ $body=json_decode(file_get_contents('php://input'),true); if(!is_array($body)||($body['status']??'')!=='completed'){http_response_code(400);exit('Payload tidak valid');} $order=q('SELECT * FROM orders WHERE invoice=?',[$body['order_id']??''])->fetch(); if(!$order||(int)$body['amount']!== (int)$order['total']){http_response_code(400);exit('Order tidak valid');} $s=q('SELECT `key`,value FROM settings WHERE `key` IN ("pakasir_slug","pakasir_api_key")')->fetchAll(PDO::FETCH_KEY_PAIR); $url='https://app.pakasir.com/api/transactiondetail?'.http_build_query(['project'=>$s['pakasir_slug']??'','amount'=>$order['total'],'order_id'=>$order['invoice'],'api_key'=>$s['pakasir_api_key']??'']); $res=@file_get_contents($url); $remote=json_decode($res ?: '',true); if(($remote['transaction']['status']??'')!=='completed'){http_response_code(403);exit('Pembayaran belum terverifikasi');} fulfill_order($order); http_response_code(200);exit('ok'); }

http_response_code(404); view('Tidak ditemukan','<section class="hero"><p class="type">404</p><h1>Halaman hilang.</h1><a class="btn" href="'.base('/').'">Ke katalog</a></section>');

function slug(string $name): string { $slug=strtolower(trim(preg_replace('/[^a-z0-9]+/i','-',iconv('UTF-8','ASCII//TRANSLIT',$name) ?: $name),'-')); return $slug?:'produk-'.bin2hex(random_bytes(3)); }
function installer_checks(): array { return [
    ['name'=>'PHP', 'value'=>PHP_VERSION.' (minimal 8.2)', 'ok'=>version_compare(PHP_VERSION,'8.2.0','>=')],
    ['name'=>'PDO MySQL', 'value'=>extension_loaded('pdo_mysql')?'Aktif':'Tidak aktif', 'ok'=>extension_loaded('pdo_mysql')],
    ['name'=>'OpenSSL', 'value'=>extension_loaded('openssl')?'Aktif':'Tidak aktif', 'ok'=>extension_loaded('openssl')],
    ['name'=>'Mbstring', 'value'=>extension_loaded('mbstring')?'Aktif':'Tidak aktif', 'ok'=>extension_loaded('mbstring')],
    ['name'=>'JSON', 'value'=>extension_loaded('json')?'Aktif':'Tidak aktif', 'ok'=>extension_loaded('json')],
    ['name'=>'storage/ dapat ditulis', 'value'=>is_writable(ROOT.'/storage')?'Writable':'Tidak writable', 'ok'=>is_dir(ROOT.'/storage') && is_writable(ROOT.'/storage')],
    ['name'=>'Root project dapat ditulis', 'value'=>is_writable(ROOT)?'Writable (.env dibuat di sini)':'Tidak writable', 'ok'=>is_writable(ROOT)],
    ['name'=>'Schema database', 'value'=>is_readable(ROOT.'/database/schema.sql')?'Terbaca':'Tidak terbaca', 'ok'=>is_readable(ROOT.'/database/schema.sql')],
]; }
function installer_ready(): bool { foreach(installer_checks() as $check)if(!$check['ok'])return false;return true; }
function installer_view(string $step,string $title,string $content): never { view('Installer','<section class="hero"><p class="type">Zenhosta setup · '.$step.'</p>'.$title.'</section><p class="muted">1. Pemeriksaan server · 2. Database · 3. Admin · 4. Lisensi</p>'.$content); }
function product_form(?array $p=null,string $action=''): string { $p??=['name'=>'','type'=>'file_link','description'=>'','price'=>'','delivery_url'=>'','active'=>1];return '<h2>'.($action?'Ubah produk':'Produk baru').'</h2><form method="post" action="'.base($action).'" ><input type="hidden" name="_csrf" value="'.csrf().'"><label>Nama produk<input name="name" value="'.e($p['name']).'" required></label><label>Tipe<select name="type"><option value="file_link" '.($p['type']==='file_link'?'selected':'').'>File / link digital</option><option value="account_stock" '.($p['type']==='account_stock'?'selected':'').'>Stok akun</option><option value="manual" '.($p['type']==='manual'?'selected':'').'>Manual</option></select></label><label>Deskripsi<textarea name="description" required>'.e($p['description']).'</textarea></label><label>Harga Rupiah<input name="price" type="number" min="0" value="'.e((string)$p['price']).'" required></label><label>Link pengiriman file/video<input name="delivery_url" type="url" value="'.e($p['delivery_url']).'" placeholder="https://drive.google.com/... "></label><p class="muted">Untuk ebook/video, isi link Google Drive, S3, R2, atau URL digital lain. Link terkirim setelah lunas.</p><label><input type="checkbox" name="active" value="1" '.($p['active']?'checked':'').'> Produk aktif</label><button>Simpan produk</button></form>'; }
function fulfill_order(array $order): void { if($order['status']!=='pending')return; db()->beginTransaction(); try { $item=q('SELECT * FROM order_items WHERE order_id=? FOR UPDATE',[$order['id']])->fetch(); $message="Terima kasih. Pesanan {$order['invoice']} sudah dibayar.\n\n"; if($item['product_type']==='account_stock'){ $stock=q("SELECT * FROM stock_items WHERE product_id=? AND status='available' ORDER BY id LIMIT 1 FOR UPDATE",[$item['product_id']])->fetch(); if(!$stock)throw new RuntimeException('Stok habis saat fulfillment'); q("UPDATE stock_items SET status='sold',order_item_id=?,sold_at=NOW() WHERE id=?",[$item['id'],$stock['id']]); $message.="Detail akun:\n".decrypt_stock($stock['payload']); } elseif($item['product_type']==='file_link'){ $message.="Link produk:\n".$item['delivery_url']; } else { $message.="Pesanan diterima. Admin akan memproses produk Anda."; } q("UPDATE order_items SET delivered_at=NOW() WHERE id=?",[$item['id']]); q("UPDATE orders SET status='fulfilled',paid_at=NOW() WHERE id=?",[$order['id']]); db()->commit(); send_mail($order['buyer_email'],'Pesanan '.$order['invoice'].' berhasil',$message); } catch(Throwable $e) { if(db()->inTransaction())db()->rollBack(); throw $e; } }
function send_mail(string $to,string $subject,string $message): void { $s=q('SELECT `key`,value FROM settings WHERE `key` LIKE "smtp_%"')->fetchAll(PDO::FETCH_KEY_PAIR); $autoload=ROOT.'/vendor/autoload.php'; if(is_file($autoload) && !empty($s['smtp_host'])) { require_once $autoload; $mail=new PHPMailer\PHPMailer\PHPMailer(true); $mail->isSMTP();$mail->Host=$s['smtp_host'];$mail->Port=(int)($s['smtp_port']?:587);$mail->SMTPAuth=true;$mail->Username=$s['smtp_user'];$mail->Password=$s['smtp_pass'];$mail->SMTPSecure=PHPMailer\PHPMailer\PHPMailer::ENCRYPTION_STARTTLS;$mail->CharSet='UTF-8';$mail->setFrom($s['smtp_from'],$s['smtp_name']?:'Toko Digital');$mail->addAddress($to);$mail->Subject=$subject;$mail->Body=$message;$mail->send();return; } @mail($to,$subject,$message,"Content-Type: text/plain; charset=UTF-8\r\n"); }
